services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${USER}
      - POSTGRES_DB=${DATABASE}
      - POSTGRES_PASSWORD=${PASSWORD}
    volumes:
      - ./SQL:/docker-entrypoint-initdb.d
    ports:
      - '5432:5432'